-- Migración para el nuevo Plan de Cuentas de Escuelas de Fútbol
-- Eliminar el plan de cuentas genérico actual para escuelas (NULL)
DELETE FROM public.plan_cuentas WHERE escuela_id IS NULL;

INSERT INTO public.plan_cuentas (codigo, nombre, tipo, es_transaccional) VALUES 
('1.1', 'Activo Corriente', 'activo', false),
('1.1.1', 'Cajas Efectivo (Gastos diarios operativos)', 'activo', false),
('1.1.2', 'Bancos (Cuentas en Banco Unión, Mercantil, Ganadero, etc.)', 'activo', false),
('1.1.3', 'Cuentas por Cobrar Alumnos (Mensualidades pendientes)', 'activo', true),
('1.1.4', 'Inventario de Indumentaria (Uniformes, medias, buzos en stock)', 'activo', true),
('1.1.5', 'Inventario de Productos (Bebidas, snacks)', 'activo', true),
('1.2', 'Activo No Corriente', 'activo', false),
('1.2.1', 'Terrenos / Instalaciones Deportivas', 'activo', true),
('1.2.2', 'Equipamiento Deportivo (Arcos, redes, máquinas de gimnasio)', 'activo', true),
('1.2.3', 'Muebles y Enseres (Oficina administrativa)', 'activo', true),
('1.2.4', 'Equipo de Computación (Sistemas de registro, Zoho, etc.)', 'activo', true),
('2.1', 'Pasivo Corriente', 'pasivo', false),
('2.1.1', 'Cuentas por Pagar Proveedores (Material deportivo, servicios)', 'pasivo', true),
('2.1.2', 'Sueldos y Salarios por Pagar', 'pasivo', true),
('2.1.3', 'Beneficios Sociales por Pagar (Previsión para finiquitos)', 'pasivo', true),
('2.1.4', 'Impuestos y Retenciones por Pagar', 'pasivo', true),
('2.1.5', 'Cobros Anticipados (Mensualidades o inscripciones pagadas por adelantado)', 'pasivo', true),
('3.1', 'Capital Social', 'patrimonio', false),
('3.2', 'Resultados Acumulados (Gestiones anteriores)', 'patrimonio', false),
('3.3', 'Resultado del Ejercicio (Gestión actual)', 'patrimonio', false),
('4.1', 'Ingresos Operativos (Actividad Principal)', 'ingreso', false),
('4.1.1', 'Ingresos por Mensualidades Fútbol', 'ingreso', true),
('4.1.2', 'Ingresos por Inscripciones a Torneos (Copa Planeta, Kalomai, etc.)', 'ingreso', true),
('4.1.3', 'Ingresos por Derechos de Formación / Traspasos (ACF)', 'ingreso', true),
('4.2', 'Venta de Bienes', 'ingreso', false),
('4.2.1', 'Venta de Uniformes (Competencia y Entrenamiento)', 'ingreso', true),
('4.2.2', 'Venta de Indumentaria de Invierno (Buzos, chamarras)', 'ingreso', true),
('4.2.3', 'Venta de Accesorios (Medias, canilleras, botiquines)', 'ingreso', true),
('4.2.4', 'Venta de Productos Consumibles (Agua, refrescos, snacks)', 'ingreso', true),
('4.3', 'Otros Ingresos', 'ingreso', false),
('4.3.1', 'Ingresos por Eventos Especiales', 'ingreso', true),
('4.3.2', 'Venta de Entradas', 'ingreso', true),
('5.1', 'Gastos de Personal', 'gasto', false),
('5.1.1', 'Sueldos y Salarios (Técnicos, administrativos, mantenimiento)', 'gasto', true),
('5.1.2', 'Bonos e Incentivos al Personal', 'gasto', true),
('5.1.3', 'Cargas Sociales y Beneficios (Finiquitos, liquidaciones)', 'gasto', true),
('5.2', 'Gastos Operativos y de Mantenimiento', 'gasto', false),
('5.2.1', 'Alquiler de Canchas e Instalaciones', 'gasto', true),
('5.2.2', 'Mantenimiento de Campos Deportivos (Arena, abonos, riego)', 'gasto', true),
('5.2.3', 'Servicios Básicos (Energía eléctrica, Agua potable, Internet)', 'gasto', true),
('5.2.4', 'Materiales y Suministros de Limpieza', 'gasto', true),
('5.2.5', 'Participación en Torneos', 'gasto', true),
('5.2.5', 'Ayuda Social', 'gasto', true),
('5.3', 'Material y Equipamiento Deportivo (Gasto Directo)', 'gasto', false),
('5.3.1', 'Insumos Deportivos (Balones, conos, pecheras)', 'gasto', true),
('5.3.2', 'Material Médico y Primeros Auxilios (Fisioterapia, botiquín)', 'gasto', true),
('5.4', 'Gastos Administrativos y de Gestión', 'gasto', false),
('5.4.1', 'Servicios Profesionales Externos (Contabilidad, Fisioterapeutas)', 'gasto', true),
('5.4.2', 'Gastos de Oficina (Papelería, útiles)', 'gasto', true),
('5.4.3', 'Licencias de Software y Publicidad', 'gasto', true),
('5.5', 'Gastos Financieros e Impuestos', 'gasto', false),
('5.5.1', 'Comisiones Bancarias / Retenciones', 'gasto', true),
('5.5.2', 'Impuestos sobre las Ventas / Débito Fiscal', 'gasto', true),
('1.1.1.01', 'Caja General', 'activo', true),
('1.1.2.01', 'Banco Unión', 'activo', true),
('1.1.2.02', 'Banco Mercantil', 'activo', true);